# Permalinks
permalink:           pretty

# Setup
title:               Fengye's Blog 
tagline:             The Jekyll Butler
url:                 http://cnepq.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              cnboy 
  url:               http://cnepq.com/
  email:             ysgdgsghc@126.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
